// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/mensagem.proto

package br.ufs.dcomp.ProtocolBuffers;

public final class SerialProto {
  private SerialProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CabecalhoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChatProtocolBuffers.Cabecalho)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string data = 1;</code>
     * @return The data.
     */
    java.lang.String getData();
    /**
     * <code>string data = 1;</code>
     * @return The bytes for data.
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <code>string hora = 2;</code>
     * @return The hora.
     */
    java.lang.String getHora();
    /**
     * <code>string hora = 2;</code>
     * @return The bytes for hora.
     */
    com.google.protobuf.ByteString
        getHoraBytes();

    /**
     * <code>string emisor = 3;</code>
     * @return The emisor.
     */
    java.lang.String getEmisor();
    /**
     * <code>string emisor = 3;</code>
     * @return The bytes for emisor.
     */
    com.google.protobuf.ByteString
        getEmisorBytes();

    /**
     * <code>string grupo = 4;</code>
     * @return The grupo.
     */
    java.lang.String getGrupo();
    /**
     * <code>string grupo = 4;</code>
     * @return The bytes for grupo.
     */
    com.google.protobuf.ByteString
        getGrupoBytes();

    /**
     * <code>string tipo = 5;</code>
     * @return The tipo.
     */
    java.lang.String getTipo();
    /**
     * <code>string tipo = 5;</code>
     * @return The bytes for tipo.
     */
    com.google.protobuf.ByteString
        getTipoBytes();
  }
  /**
   * Protobuf type {@code ChatProtocolBuffers.Cabecalho}
   */
  public  static final class Cabecalho extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ChatProtocolBuffers.Cabecalho)
      CabecalhoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Cabecalho.newBuilder() to construct.
    private Cabecalho(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Cabecalho() {
      data_ = "";
      hora_ = "";
      emisor_ = "";
      grupo_ = "";
      tipo_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Cabecalho();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Cabecalho(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              hora_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              emisor_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              grupo_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              tipo_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ufs.dcomp.ProtocolBuffers.SerialProto.internal_static_ChatProtocolBuffers_Cabecalho_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ufs.dcomp.ProtocolBuffers.SerialProto.internal_static_ChatProtocolBuffers_Cabecalho_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho.class, br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho.Builder.class);
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private volatile java.lang.Object data_;
    /**
     * <code>string data = 1;</code>
     * @return The data.
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <code>string data = 1;</code>
     * @return The bytes for data.
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HORA_FIELD_NUMBER = 2;
    private volatile java.lang.Object hora_;
    /**
     * <code>string hora = 2;</code>
     * @return The hora.
     */
    public java.lang.String getHora() {
      java.lang.Object ref = hora_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hora_ = s;
        return s;
      }
    }
    /**
     * <code>string hora = 2;</code>
     * @return The bytes for hora.
     */
    public com.google.protobuf.ByteString
        getHoraBytes() {
      java.lang.Object ref = hora_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hora_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMISOR_FIELD_NUMBER = 3;
    private volatile java.lang.Object emisor_;
    /**
     * <code>string emisor = 3;</code>
     * @return The emisor.
     */
    public java.lang.String getEmisor() {
      java.lang.Object ref = emisor_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        emisor_ = s;
        return s;
      }
    }
    /**
     * <code>string emisor = 3;</code>
     * @return The bytes for emisor.
     */
    public com.google.protobuf.ByteString
        getEmisorBytes() {
      java.lang.Object ref = emisor_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        emisor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GRUPO_FIELD_NUMBER = 4;
    private volatile java.lang.Object grupo_;
    /**
     * <code>string grupo = 4;</code>
     * @return The grupo.
     */
    public java.lang.String getGrupo() {
      java.lang.Object ref = grupo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        grupo_ = s;
        return s;
      }
    }
    /**
     * <code>string grupo = 4;</code>
     * @return The bytes for grupo.
     */
    public com.google.protobuf.ByteString
        getGrupoBytes() {
      java.lang.Object ref = grupo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        grupo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIPO_FIELD_NUMBER = 5;
    private volatile java.lang.Object tipo_;
    /**
     * <code>string tipo = 5;</code>
     * @return The tipo.
     */
    public java.lang.String getTipo() {
      java.lang.Object ref = tipo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tipo_ = s;
        return s;
      }
    }
    /**
     * <code>string tipo = 5;</code>
     * @return The bytes for tipo.
     */
    public com.google.protobuf.ByteString
        getTipoBytes() {
      java.lang.Object ref = tipo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tipo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, data_);
      }
      if (!getHoraBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, hora_);
      }
      if (!getEmisorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, emisor_);
      }
      if (!getGrupoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, grupo_);
      }
      if (!getTipoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, tipo_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, data_);
      }
      if (!getHoraBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, hora_);
      }
      if (!getEmisorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, emisor_);
      }
      if (!getGrupoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, grupo_);
      }
      if (!getTipoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, tipo_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho)) {
        return super.equals(obj);
      }
      br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho other = (br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho) obj;

      if (!getData()
          .equals(other.getData())) return false;
      if (!getHora()
          .equals(other.getHora())) return false;
      if (!getEmisor()
          .equals(other.getEmisor())) return false;
      if (!getGrupo()
          .equals(other.getGrupo())) return false;
      if (!getTipo()
          .equals(other.getTipo())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + HORA_FIELD_NUMBER;
      hash = (53 * hash) + getHora().hashCode();
      hash = (37 * hash) + EMISOR_FIELD_NUMBER;
      hash = (53 * hash) + getEmisor().hashCode();
      hash = (37 * hash) + GRUPO_FIELD_NUMBER;
      hash = (53 * hash) + getGrupo().hashCode();
      hash = (37 * hash) + TIPO_FIELD_NUMBER;
      hash = (53 * hash) + getTipo().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChatProtocolBuffers.Cabecalho}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChatProtocolBuffers.Cabecalho)
        br.ufs.dcomp.ProtocolBuffers.SerialProto.CabecalhoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.ufs.dcomp.ProtocolBuffers.SerialProto.internal_static_ChatProtocolBuffers_Cabecalho_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.ufs.dcomp.ProtocolBuffers.SerialProto.internal_static_ChatProtocolBuffers_Cabecalho_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho.class, br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho.Builder.class);
      }

      // Construct using br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        data_ = "";

        hora_ = "";

        emisor_ = "";

        grupo_ = "";

        tipo_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.ufs.dcomp.ProtocolBuffers.SerialProto.internal_static_ChatProtocolBuffers_Cabecalho_descriptor;
      }

      @java.lang.Override
      public br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho getDefaultInstanceForType() {
        return br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho.getDefaultInstance();
      }

      @java.lang.Override
      public br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho build() {
        br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho buildPartial() {
        br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho result = new br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho(this);
        result.data_ = data_;
        result.hora_ = hora_;
        result.emisor_ = emisor_;
        result.grupo_ = grupo_;
        result.tipo_ = tipo_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho) {
          return mergeFrom((br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho other) {
        if (other == br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho.getDefaultInstance()) return this;
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        if (!other.getHora().isEmpty()) {
          hora_ = other.hora_;
          onChanged();
        }
        if (!other.getEmisor().isEmpty()) {
          emisor_ = other.emisor_;
          onChanged();
        }
        if (!other.getGrupo().isEmpty()) {
          grupo_ = other.grupo_;
          onChanged();
        }
        if (!other.getTipo().isEmpty()) {
          tipo_ = other.tipo_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <code>string data = 1;</code>
       * @return The data.
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string data = 1;</code>
       * @return The bytes for data.
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string data = 1;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string data = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>string data = 1;</code>
       * @param value The bytes for data to set.
       * @return This builder for chaining.
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object hora_ = "";
      /**
       * <code>string hora = 2;</code>
       * @return The hora.
       */
      public java.lang.String getHora() {
        java.lang.Object ref = hora_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hora_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string hora = 2;</code>
       * @return The bytes for hora.
       */
      public com.google.protobuf.ByteString
          getHoraBytes() {
        java.lang.Object ref = hora_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hora_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string hora = 2;</code>
       * @param value The hora to set.
       * @return This builder for chaining.
       */
      public Builder setHora(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hora_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string hora = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearHora() {
        
        hora_ = getDefaultInstance().getHora();
        onChanged();
        return this;
      }
      /**
       * <code>string hora = 2;</code>
       * @param value The bytes for hora to set.
       * @return This builder for chaining.
       */
      public Builder setHoraBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hora_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object emisor_ = "";
      /**
       * <code>string emisor = 3;</code>
       * @return The emisor.
       */
      public java.lang.String getEmisor() {
        java.lang.Object ref = emisor_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          emisor_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string emisor = 3;</code>
       * @return The bytes for emisor.
       */
      public com.google.protobuf.ByteString
          getEmisorBytes() {
        java.lang.Object ref = emisor_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          emisor_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string emisor = 3;</code>
       * @param value The emisor to set.
       * @return This builder for chaining.
       */
      public Builder setEmisor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        emisor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string emisor = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmisor() {
        
        emisor_ = getDefaultInstance().getEmisor();
        onChanged();
        return this;
      }
      /**
       * <code>string emisor = 3;</code>
       * @param value The bytes for emisor to set.
       * @return This builder for chaining.
       */
      public Builder setEmisorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        emisor_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object grupo_ = "";
      /**
       * <code>string grupo = 4;</code>
       * @return The grupo.
       */
      public java.lang.String getGrupo() {
        java.lang.Object ref = grupo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          grupo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string grupo = 4;</code>
       * @return The bytes for grupo.
       */
      public com.google.protobuf.ByteString
          getGrupoBytes() {
        java.lang.Object ref = grupo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          grupo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string grupo = 4;</code>
       * @param value The grupo to set.
       * @return This builder for chaining.
       */
      public Builder setGrupo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        grupo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string grupo = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearGrupo() {
        
        grupo_ = getDefaultInstance().getGrupo();
        onChanged();
        return this;
      }
      /**
       * <code>string grupo = 4;</code>
       * @param value The bytes for grupo to set.
       * @return This builder for chaining.
       */
      public Builder setGrupoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        grupo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tipo_ = "";
      /**
       * <code>string tipo = 5;</code>
       * @return The tipo.
       */
      public java.lang.String getTipo() {
        java.lang.Object ref = tipo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tipo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tipo = 5;</code>
       * @return The bytes for tipo.
       */
      public com.google.protobuf.ByteString
          getTipoBytes() {
        java.lang.Object ref = tipo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tipo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tipo = 5;</code>
       * @param value The tipo to set.
       * @return This builder for chaining.
       */
      public Builder setTipo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tipo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tipo = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTipo() {
        
        tipo_ = getDefaultInstance().getTipo();
        onChanged();
        return this;
      }
      /**
       * <code>string tipo = 5;</code>
       * @param value The bytes for tipo to set.
       * @return This builder for chaining.
       */
      public Builder setTipoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tipo_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ChatProtocolBuffers.Cabecalho)
    }

    // @@protoc_insertion_point(class_scope:ChatProtocolBuffers.Cabecalho)
    private static final br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho();
    }

    public static br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Cabecalho>
        PARSER = new com.google.protobuf.AbstractParser<Cabecalho>() {
      @java.lang.Override
      public Cabecalho parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Cabecalho(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Cabecalho> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Cabecalho> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MensagemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChatProtocolBuffers.Mensagem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ChatProtocolBuffers.Cabecalho cabecalho = 1;</code>
     * @return Whether the cabecalho field is set.
     */
    boolean hasCabecalho();
    /**
     * <code>.ChatProtocolBuffers.Cabecalho cabecalho = 1;</code>
     * @return The cabecalho.
     */
    br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho getCabecalho();
    /**
     * <code>.ChatProtocolBuffers.Cabecalho cabecalho = 1;</code>
     */
    br.ufs.dcomp.ProtocolBuffers.SerialProto.CabecalhoOrBuilder getCabecalhoOrBuilder();

    /**
     * <code>string nome_conteudo = 2;</code>
     * @return The nomeConteudo.
     */
    java.lang.String getNomeConteudo();
    /**
     * <code>string nome_conteudo = 2;</code>
     * @return The bytes for nomeConteudo.
     */
    com.google.protobuf.ByteString
        getNomeConteudoBytes();

    /**
     * <code>bytes conteudo = 3;</code>
     * @return The conteudo.
     */
    com.google.protobuf.ByteString getConteudo();
  }
  /**
   * Protobuf type {@code ChatProtocolBuffers.Mensagem}
   */
  public  static final class Mensagem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ChatProtocolBuffers.Mensagem)
      MensagemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Mensagem.newBuilder() to construct.
    private Mensagem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Mensagem() {
      nomeConteudo_ = "";
      conteudo_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Mensagem();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Mensagem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho.Builder subBuilder = null;
              if (cabecalho_ != null) {
                subBuilder = cabecalho_.toBuilder();
              }
              cabecalho_ = input.readMessage(br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(cabecalho_);
                cabecalho_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              nomeConteudo_ = s;
              break;
            }
            case 26: {

              conteudo_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ufs.dcomp.ProtocolBuffers.SerialProto.internal_static_ChatProtocolBuffers_Mensagem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ufs.dcomp.ProtocolBuffers.SerialProto.internal_static_ChatProtocolBuffers_Mensagem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem.class, br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem.Builder.class);
    }

    public static final int CABECALHO_FIELD_NUMBER = 1;
    private br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho cabecalho_;
    /**
     * <code>.ChatProtocolBuffers.Cabecalho cabecalho = 1;</code>
     * @return Whether the cabecalho field is set.
     */
    public boolean hasCabecalho() {
      return cabecalho_ != null;
    }
    /**
     * <code>.ChatProtocolBuffers.Cabecalho cabecalho = 1;</code>
     * @return The cabecalho.
     */
    public br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho getCabecalho() {
      return cabecalho_ == null ? br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho.getDefaultInstance() : cabecalho_;
    }
    /**
     * <code>.ChatProtocolBuffers.Cabecalho cabecalho = 1;</code>
     */
    public br.ufs.dcomp.ProtocolBuffers.SerialProto.CabecalhoOrBuilder getCabecalhoOrBuilder() {
      return getCabecalho();
    }

    public static final int NOME_CONTEUDO_FIELD_NUMBER = 2;
    private volatile java.lang.Object nomeConteudo_;
    /**
     * <code>string nome_conteudo = 2;</code>
     * @return The nomeConteudo.
     */
    public java.lang.String getNomeConteudo() {
      java.lang.Object ref = nomeConteudo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nomeConteudo_ = s;
        return s;
      }
    }
    /**
     * <code>string nome_conteudo = 2;</code>
     * @return The bytes for nomeConteudo.
     */
    public com.google.protobuf.ByteString
        getNomeConteudoBytes() {
      java.lang.Object ref = nomeConteudo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nomeConteudo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTEUDO_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString conteudo_;
    /**
     * <code>bytes conteudo = 3;</code>
     * @return The conteudo.
     */
    public com.google.protobuf.ByteString getConteudo() {
      return conteudo_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cabecalho_ != null) {
        output.writeMessage(1, getCabecalho());
      }
      if (!getNomeConteudoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nomeConteudo_);
      }
      if (!conteudo_.isEmpty()) {
        output.writeBytes(3, conteudo_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cabecalho_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCabecalho());
      }
      if (!getNomeConteudoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nomeConteudo_);
      }
      if (!conteudo_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, conteudo_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem)) {
        return super.equals(obj);
      }
      br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem other = (br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem) obj;

      if (hasCabecalho() != other.hasCabecalho()) return false;
      if (hasCabecalho()) {
        if (!getCabecalho()
            .equals(other.getCabecalho())) return false;
      }
      if (!getNomeConteudo()
          .equals(other.getNomeConteudo())) return false;
      if (!getConteudo()
          .equals(other.getConteudo())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCabecalho()) {
        hash = (37 * hash) + CABECALHO_FIELD_NUMBER;
        hash = (53 * hash) + getCabecalho().hashCode();
      }
      hash = (37 * hash) + NOME_CONTEUDO_FIELD_NUMBER;
      hash = (53 * hash) + getNomeConteudo().hashCode();
      hash = (37 * hash) + CONTEUDO_FIELD_NUMBER;
      hash = (53 * hash) + getConteudo().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChatProtocolBuffers.Mensagem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChatProtocolBuffers.Mensagem)
        br.ufs.dcomp.ProtocolBuffers.SerialProto.MensagemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.ufs.dcomp.ProtocolBuffers.SerialProto.internal_static_ChatProtocolBuffers_Mensagem_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.ufs.dcomp.ProtocolBuffers.SerialProto.internal_static_ChatProtocolBuffers_Mensagem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem.class, br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem.Builder.class);
      }

      // Construct using br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (cabecalhoBuilder_ == null) {
          cabecalho_ = null;
        } else {
          cabecalho_ = null;
          cabecalhoBuilder_ = null;
        }
        nomeConteudo_ = "";

        conteudo_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.ufs.dcomp.ProtocolBuffers.SerialProto.internal_static_ChatProtocolBuffers_Mensagem_descriptor;
      }

      @java.lang.Override
      public br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem getDefaultInstanceForType() {
        return br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem.getDefaultInstance();
      }

      @java.lang.Override
      public br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem build() {
        br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem buildPartial() {
        br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem result = new br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem(this);
        if (cabecalhoBuilder_ == null) {
          result.cabecalho_ = cabecalho_;
        } else {
          result.cabecalho_ = cabecalhoBuilder_.build();
        }
        result.nomeConteudo_ = nomeConteudo_;
        result.conteudo_ = conteudo_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem) {
          return mergeFrom((br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem other) {
        if (other == br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem.getDefaultInstance()) return this;
        if (other.hasCabecalho()) {
          mergeCabecalho(other.getCabecalho());
        }
        if (!other.getNomeConteudo().isEmpty()) {
          nomeConteudo_ = other.nomeConteudo_;
          onChanged();
        }
        if (other.getConteudo() != com.google.protobuf.ByteString.EMPTY) {
          setConteudo(other.getConteudo());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho cabecalho_;
      private com.google.protobuf.SingleFieldBuilderV3<
          br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho, br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho.Builder, br.ufs.dcomp.ProtocolBuffers.SerialProto.CabecalhoOrBuilder> cabecalhoBuilder_;
      /**
       * <code>.ChatProtocolBuffers.Cabecalho cabecalho = 1;</code>
       * @return Whether the cabecalho field is set.
       */
      public boolean hasCabecalho() {
        return cabecalhoBuilder_ != null || cabecalho_ != null;
      }
      /**
       * <code>.ChatProtocolBuffers.Cabecalho cabecalho = 1;</code>
       * @return The cabecalho.
       */
      public br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho getCabecalho() {
        if (cabecalhoBuilder_ == null) {
          return cabecalho_ == null ? br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho.getDefaultInstance() : cabecalho_;
        } else {
          return cabecalhoBuilder_.getMessage();
        }
      }
      /**
       * <code>.ChatProtocolBuffers.Cabecalho cabecalho = 1;</code>
       */
      public Builder setCabecalho(br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho value) {
        if (cabecalhoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cabecalho_ = value;
          onChanged();
        } else {
          cabecalhoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.ChatProtocolBuffers.Cabecalho cabecalho = 1;</code>
       */
      public Builder setCabecalho(
          br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho.Builder builderForValue) {
        if (cabecalhoBuilder_ == null) {
          cabecalho_ = builderForValue.build();
          onChanged();
        } else {
          cabecalhoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.ChatProtocolBuffers.Cabecalho cabecalho = 1;</code>
       */
      public Builder mergeCabecalho(br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho value) {
        if (cabecalhoBuilder_ == null) {
          if (cabecalho_ != null) {
            cabecalho_ =
              br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho.newBuilder(cabecalho_).mergeFrom(value).buildPartial();
          } else {
            cabecalho_ = value;
          }
          onChanged();
        } else {
          cabecalhoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.ChatProtocolBuffers.Cabecalho cabecalho = 1;</code>
       */
      public Builder clearCabecalho() {
        if (cabecalhoBuilder_ == null) {
          cabecalho_ = null;
          onChanged();
        } else {
          cabecalho_ = null;
          cabecalhoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.ChatProtocolBuffers.Cabecalho cabecalho = 1;</code>
       */
      public br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho.Builder getCabecalhoBuilder() {
        
        onChanged();
        return getCabecalhoFieldBuilder().getBuilder();
      }
      /**
       * <code>.ChatProtocolBuffers.Cabecalho cabecalho = 1;</code>
       */
      public br.ufs.dcomp.ProtocolBuffers.SerialProto.CabecalhoOrBuilder getCabecalhoOrBuilder() {
        if (cabecalhoBuilder_ != null) {
          return cabecalhoBuilder_.getMessageOrBuilder();
        } else {
          return cabecalho_ == null ?
              br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho.getDefaultInstance() : cabecalho_;
        }
      }
      /**
       * <code>.ChatProtocolBuffers.Cabecalho cabecalho = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho, br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho.Builder, br.ufs.dcomp.ProtocolBuffers.SerialProto.CabecalhoOrBuilder> 
          getCabecalhoFieldBuilder() {
        if (cabecalhoBuilder_ == null) {
          cabecalhoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho, br.ufs.dcomp.ProtocolBuffers.SerialProto.Cabecalho.Builder, br.ufs.dcomp.ProtocolBuffers.SerialProto.CabecalhoOrBuilder>(
                  getCabecalho(),
                  getParentForChildren(),
                  isClean());
          cabecalho_ = null;
        }
        return cabecalhoBuilder_;
      }

      private java.lang.Object nomeConteudo_ = "";
      /**
       * <code>string nome_conteudo = 2;</code>
       * @return The nomeConteudo.
       */
      public java.lang.String getNomeConteudo() {
        java.lang.Object ref = nomeConteudo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nomeConteudo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nome_conteudo = 2;</code>
       * @return The bytes for nomeConteudo.
       */
      public com.google.protobuf.ByteString
          getNomeConteudoBytes() {
        java.lang.Object ref = nomeConteudo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nomeConteudo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nome_conteudo = 2;</code>
       * @param value The nomeConteudo to set.
       * @return This builder for chaining.
       */
      public Builder setNomeConteudo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nomeConteudo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nome_conteudo = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNomeConteudo() {
        
        nomeConteudo_ = getDefaultInstance().getNomeConteudo();
        onChanged();
        return this;
      }
      /**
       * <code>string nome_conteudo = 2;</code>
       * @param value The bytes for nomeConteudo to set.
       * @return This builder for chaining.
       */
      public Builder setNomeConteudoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nomeConteudo_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString conteudo_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes conteudo = 3;</code>
       * @return The conteudo.
       */
      public com.google.protobuf.ByteString getConteudo() {
        return conteudo_;
      }
      /**
       * <code>bytes conteudo = 3;</code>
       * @param value The conteudo to set.
       * @return This builder for chaining.
       */
      public Builder setConteudo(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        conteudo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes conteudo = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearConteudo() {
        
        conteudo_ = getDefaultInstance().getConteudo();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ChatProtocolBuffers.Mensagem)
    }

    // @@protoc_insertion_point(class_scope:ChatProtocolBuffers.Mensagem)
    private static final br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem();
    }

    public static br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Mensagem>
        PARSER = new com.google.protobuf.AbstractParser<Mensagem>() {
      @java.lang.Override
      public Mensagem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Mensagem(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Mensagem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Mensagem> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public br.ufs.dcomp.ProtocolBuffers.SerialProto.Mensagem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatProtocolBuffers_Cabecalho_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChatProtocolBuffers_Cabecalho_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatProtocolBuffers_Mensagem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChatProtocolBuffers_Mensagem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035src/main/proto/mensagem.proto\022\023ChatPro" +
      "tocolBuffers\"T\n\tCabecalho\022\014\n\004data\030\001 \001(\t\022" +
      "\014\n\004hora\030\002 \001(\t\022\016\n\006emisor\030\003 \001(\t\022\r\n\005grupo\030\004" +
      " \001(\t\022\014\n\004tipo\030\005 \001(\t\"f\n\010Mensagem\0221\n\tcabeca" +
      "lho\030\001 \001(\0132\036.ChatProtocolBuffers.Cabecalh" +
      "o\022\025\n\rnome_conteudo\030\002 \001(\t\022\020\n\010conteudo\030\003 \001" +
      "(\014B+\n\034br.ufs.dcomp.ProtocolBuffersB\013Seri" +
      "alProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ChatProtocolBuffers_Cabecalho_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ChatProtocolBuffers_Cabecalho_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChatProtocolBuffers_Cabecalho_descriptor,
        new java.lang.String[] { "Data", "Hora", "Emisor", "Grupo", "Tipo", });
    internal_static_ChatProtocolBuffers_Mensagem_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ChatProtocolBuffers_Mensagem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChatProtocolBuffers_Mensagem_descriptor,
        new java.lang.String[] { "Cabecalho", "NomeConteudo", "Conteudo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
